FROM php:8.2-fpm

# Prepare the image with all necessary dependencies for PHP
RUN apt update && apt install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev 

RUN apt clean && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Copy the official Composer binary into the image
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
