# Usa una imagen base oficial de Node.js
FROM node:16
# Establece el directorio de trabajo en el contenedor
WORKDIR /laravel/node
# Copia los archivos package.json y package-lock.json al contenedor
COPY package*.json ./
# Instala las dependencias de la aplicación
RUN npm install
# Copia el resto del código de la aplicación
COPY . .
# Expone el puerto en el que corre la aplicación (ajusta según tu configuración)
EXPOSE 3000
# Comando por defecto para correr la aplicación
CMD ["node", "server.js"]
