# Usa una imagen de Node.js como base
FROM node:18

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instala las dependencias de Vue.js
RUN npm install

# Copia todo el código fuente al contenedor
COPY . .

# Asegura permisos correctos para el directorio y subdirectorios
RUN chown -R node:node /app && chmod -R 755 /app

# Cambia a un usuario no root para ejecutar la aplicación (seguridad adicional)
USER node

# Expón el puerto que usará el servidor de desarrollo
EXPOSE 8080

# Comando para ejecutar el servidor de desarrollo de Vue.js
CMD ["npm", "run", "dev"]
